#server:
#  port: 80
#
#eureka:
#  client:
#    service-url: 
#      defaultZone: http://eureka7001.com:7001,http://eureka7002.com:7002,http://eureka7003.com:7003
#      instance:
#        instance-id: ServiceRibbonApplication
#        prefer-ip-address: true     #访问路径可以显示IP地址

#server:
#  port: 80
#spring:
#  application:
#    name: microservicecloud-dept
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      #defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: ServiceRibbonApplication
#    prefer-ip-address: true     #访问路径可以显示IP地址

server:
  port: 80
spring:
  application:
    name: microservicecloud-fegin

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-fegin80
    prefer-ip-address: true     #访问路径可以显示IP地址
