server:
  port: 8010

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-security8010
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: microservicecloud-security
  company.name: www.lei.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

# 安全认证的配置
spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: microservicecloud-security
